// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpYn63JGoMCczZ6W-7bXqgs8ZzJeXVNUc',
    appId: '1:91757204726:web:e7d43fa811a71d742b48d7',
    messagingSenderId: '91757204726',
    projectId: 'petadopt-36583',
    authDomain: 'petadopt-36583.firebaseapp.com',
    storageBucket: 'petadopt-36583.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7YazGr0BMxx_UFcc2onaux7b4dAEAxY',
    appId: '1:91757204726:android:f6318a85c1aea1fd2b48d7',
    messagingSenderId: '91757204726',
    projectId: 'petadopt-36583',
    storageBucket: 'petadopt-36583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7xcV5vbax2nr3C9Ij-k2b-VpkAfSoDo',
    appId: '1:91757204726:ios:b2e285b69abba1d42b48d7',
    messagingSenderId: '91757204726',
    projectId: 'petadopt-36583',
    storageBucket: 'petadopt-36583.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX7xcV5vbax2nr3C9Ij-k2b-VpkAfSoDo',
    appId: '1:91757204726:ios:b2e285b69abba1d42b48d7',
    messagingSenderId: '91757204726',
    projectId: 'petadopt-36583',
    storageBucket: 'petadopt-36583.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpYn63JGoMCczZ6W-7bXqgs8ZzJeXVNUc',
    appId: '1:91757204726:web:5d3eb79efa1626822b48d7',
    messagingSenderId: '91757204726',
    projectId: 'petadopt-36583',
    authDomain: 'petadopt-36583.firebaseapp.com',
    storageBucket: 'petadopt-36583.firebasestorage.app',
  );
}
